from Components import WireC, BoardPinC, PinDict
from Values import Levels

def W(SideIndex, Name = ''):
    return ((PinDict.W, SideIndex), Name)
def E(SideIndex, Name = ''):
    return ((PinDict.E, SideIndex), Name)
def N(SideIndex, Name = ''):
    return ((PinDict.N, SideIndex), Name)
def S(SideIndex, Name = ''):
    return ((PinDict.S, SideIndex), Name)

Definitions = {
    'Wire' :(WireC, 'w'),
    'I/O'  :(BoardPinC, 'i'),
    'And'  :(([W(0),
               W(1)],
              [E(0)],
        lambda a, b: (a & b,), 
        False,
        None, 
        None, 
        None, 
        0b11,
        '&'), 'a'),
    'Or' :(([W(0),
             W(1)],
            [E(0)],
        lambda a, b: (a | b,) , # Need this to allow for undef run
        False,
        None, 
        None, 
        None, 
        0b11,
        '|'), 'o'),
    'XOr' :(([W(0),
             W(1)],
            [E(0)],
        lambda a, b: (a ^ b,) , 
        False,
        None, 
        None, 
        None, 
        0b11,
        '^'), 'x'),
    'Not':(([W(0, 'in')],
            [E(0, 'out')],
        lambda a   : (not a,)  , 
        False,
        None, 
        None, 
        None, 
        0b01,
        '~'), 'n'),
    'High' :(([],
        [E(0)],
        lambda     : (True,)   , 
        False,
        None, 
        None, 
        None,
        0b00,
        '+'),  'h'),
    'Low':(([],
        [E(0)],
        lambda     : (False,)  , 
        False,
        None, 
        None, 
        None,
        0b00,
        '-'), 'l'),
    'Set':(([W(0, 'in')],
        [E(0, 'out')],
        lambda a    : (Levels.High if a == Levels.High else Levels.Low,)  , 
        True,
        None, 
        None, 
        None,
        0b01,
        '='), 'q'),
}
